# Generated by Django 5.1.4 on 2025-02-10 16:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
