# Generated by Django 5.1.4 on 2025-02-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('qualification', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=13)),
                ('address', models.TextField()),
                ('join_date', models.DateField()),
                ('position', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='teachers/')),
                ('employment_type', models.CharField(choices=[('full', 'Full Time'), ('part', 'Part Time'), ('contract', 'Contract')], max_length=8)),
                ('status', models.CharField(choices=[('ac', 'Active'), ('in', 'Inactive'), ('pd', 'Pending')], default='in', max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
